### ISSUE TITLE
V1 API support removal

### ISSUE THREAD

**Issue by matthewhartstonge** [jlinn/pyflare#11]
Hey team,

Just having a look into your repo and noticed on the endpoint you are currently using it states "CloudFlare is removing support for this API on November 9th, 2016". Not sure if this means removing the API, or simply getting rid of the documentation and all support tickets will be 'binned'. Do you have any indication on if they are shutting down the API?

I've found a migration guide but not much else: https://www.cloudflare.com/migrating-to-v4/

Looks like the Hosting API on the other hand is still set @ v1.1.1.

**Comment by jlinn** [comment]
Looks like they'll be shutting down v1 in November.  I'll take a look at the v4 docs this weekend.  Thanks for the heads-up.

**Comment by matthewhartstonge** [comment]
You're welcome! Thanks for your lib!
